  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install packages
        run: yarn install --frozen-lockfile --non-interactive
      - name: Run lint
        run: yarn lint
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install packages
        run: yarn install --frozen-lockfile --non-interactive
      - name: Run the unit tests
        run: yarn test